server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infinitemusic?serverTimezone=UTC
    username: root
    password: 3306


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

